# This is the playbook to create an EC2 instances from AMI

---

- hosts: aws
  #connection: local
  gather_facts: False

  vars:
    key_name: my_aws
    region: eu-west-1
    image: ami-07af865ccd4f26e56
    id: "eng67.bari.app.ansible"
    sec_group: "sg-0e27cbf924f9eeb73"
    subnet_id: "subnet-0429d69d55dfad9d2"

  tasks:

    - name: Facts
      - name: Get instances facts
        ec2_instance_facts:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "{{ region }}"
        register: result

    - name: Provisioning EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"

       - name: Provision instance(s)
        ec2:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          assign_public_ip: true
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          group_id: "{{ sec_group }}"
          #public subnet id
          vpc_subnet_id: "{{ subnet_id }}"
           image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
          # exact_count: 2
          # count_tag:
          #   Name: App
          # instance_tags:
          #   Name: App
      tags: ['never', 'create_ec2']
