---

# This is a YAML file to install nginx onto oue web VM using YAML
---

- hosts: db

  gather_facts: yes

  become: true

  tasks:
  - name: install mongodb
    apt: pkg=mongodb state=present

  - name: Remove mongodb file (delete file)
    file:
      path: /etc/mongodb.conf
      state: absent

  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /etc/mongodb.conf
      state: touch
      mode: u=rw,g=r,o=r


  - name: Insert multiple lines and Backup
    blockinfile:
      path: /etc/mongodb.conf
      block: |
        # mongodb.conf
        storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log

        net:
          port: 27017
          bindIp: 0.0.0.0

  - name: Restart mongodb
    become: true
    shell: systemctl restart mongodb

  - name: enable mongodb
    become: true
    shell: systemctl enable mongodb

  - name: start mongodb
    become: true
    shell: systemctl start mongodb


# where do we want to install
- hosts: web

# get the facts
  gather_facts: yes

# changes access to root user
  become: true

# what do we want ansible to do for us in the playbook
# In this case our only task is to install nginx

  tasks:
  - name: Install nginx
    apt: pkg=nginx state=present
    become_user: root

  - name: Install Nginx
    apt: pkg=nginx state=present

  - name: Remove nginx default files - sites available
    shell: rm /etc/nginx/sites-available/default.conf

  - name: Remove nginx default files - sites enabled
    shell: rm /etc/nginx/sites-enabled/default.conf

  - name: Copy nginx default file
    shell: cp /home/vagrant/app/nginx.conf /etc/nginx/sites-available/default.conf

  - name: Symlink from sites available to sites enabled
    shell: ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf

  - name: Restart nginx
    shell: service nginx restart

  - name: Install nodejs
    apt: pkg=nodejs state=present

  - name: Install NPM
    apt: pkg=npm state=present

# Downloading pm2
  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: download latest npm
    shell: |
      npm install -g npm@latest
      npm install mongoose -y


  - name: set up app
    shell: |
      cd app/
      npm install
      node seeds/seed.js
      pm2 kill
      pm2 start app.js
    environment:
      DB_HOST: mongodb://vagrant@192.168.33.11:27017/posts?authSource=admin
    become_user: root
